config/routes.rb
Rails.application.routes.draw do
  get 'foods/index'

  get 'foods/show.:id', to: 'foods#show', as: 'show', id: /\d+/

  get 'pages/lizards'

  get 'pages/home', to: 'pages#home', as: 'home'

  get 'pages/about_us', to: 'pages#about', as: 'about'

  get 'lizards/:number', to: 'pages#lizards', as: 'lizard', number: /\d+/

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :type, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def lizards
    @number = params[:number]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/common/_menu.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Lizards - 12', lizard_path(12)  %></li>
      <li><%= link_to 'Lizards - 444', lizard_path(444)  %></li>
      <li><%= link_to 'Lizards - 9672', lizard_path(9672)  %></li>
    </ul>
  </nav>
<header>

app/views/foods/_food.html.erb
<p>
<% if display_food_link %>
  Dish: <%= link_to food.dish, show_path(food) %>
<% else %>
  Dish: <%= food.dish %>
<% end %>
</p>

app/views/foods/index.html.erb
<h1>Foods#index</h1>
<% @foods.each do |food| %>
  <%= render partial: 'food', object: food, locals: { display_food_link: true } %>
<% end %>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<%= render partial: 'food', object: @food, locals: { display_food_link: false } %>
<p><b>Ingredient:</b> <%= @food.ingredients %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SickChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/menu' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>Pages#about</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultricies ex ligula, ac accumsan mauris euismod vel. Duis ut mauris sit amet orci ultrices luctus. Donec dapibus a arcu in malesuada. Phasellus sed porta libero. Vestibulum molestie diam vitae nisl posuere iaculis. Maecenas et erat arcu. Fusce aliquam ligula id ex varius suscipit. Nullam vitae nibh euismod, mattis odio sed, malesuada nulla. Etiam vel mauris eget eros vehicula malesuada id non mauris.

Aenean vitae ornare neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas rhoncus sem feugiat mi ultrices tristique. Pellentesque vel efficitur eros. Praesent iaculis ac mauris nec porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam tempor dui dolor, nec iaculis mauris consectetur ut. Maecenas euismod eros sit amet suscipit eleifend. Suspendisse vitae sagittis ligula, eget lobortis urna. Aenean porttitor lorem tempus lacinia auctor. Ut dignissim mollis turpis sed auctor. In tempus, ipsum eget aliquam venenatis, felis nisi congue ligula, a porta neque nunc eget odio. Nunc vel finibus eros. Praesent nisi elit, fermentum at faucibus quis, semper id nunc. Morbi faucibus odio diam, id gravida lacus blandit nec.</p>

app/views/pages/home.html.erb
<h2>Home</h2>
<p>Etiam est nulla, ullamcorper in metus vel, sollicitudin dapibus risus. Pellentesque lacinia id enim at hendrerit. In imperdiet dictum auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ultricies iaculis orci, non lacinia sapien consequat eu. Morbi finibus nec orci sed condimentum. Morbi ut justo ut eros laoreet tincidunt sollicitudin aliquam turpis. Maecenas pellentesque massa mi, eu semper felis blandit ac. Vestibulum et libero eget nibh feugiat dapibus. Sed maximus mi ut ipsum dignissim cursus eu id magna. Donec a lobortis nibh. Etiam orci ipsum, aliquam eget laoreet eget, posuere quis arcu. Integer nec lorem dignissim, posuere velit sit amet, posuere dolor.

Nulla vulputate mi id finibus rhoncus. Aenean non elit metus. Pellentesque vestibulum tempor sapien et vulputate. Proin tristique lacus sit amet nunc elementum placerat. Donec suscipit sagittis ligula in vehicula. Duis tincidunt arcu a ex ullamcorper feugiat. Aenean lacinia, velit viverra ullamcorper ultrices, sem purus dignissim nisi, nec dapibus lacus odio ut felis. Sed at libero leo. Quisque maximus pretium scelerisque. Suspendisse quis laoreet lectus, in efficitur sem.</p>

app/views/pages/lizards.html.erb
<h1>Lizards</h1>
<% (@number.to_i).times do %>
<%= "🦎" %>
<% end %>